In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import glob

In [2]:
root_path = os.getcwd()
root_path

'/home/jayesh/Documents/ML&DL_stuff/NorthEastern_SMILE/recognizing-faces-in-the-wild'

In [3]:
#len([i for i in os.listdir(root_path + "/train") if os.path.isdir(i)])

In [4]:
F = []

In [5]:
count_F = {}

In [6]:
dataset = pd.read_csv('train_relationships.csv')
print(dataset.shape)
related = np.zeros((dataset.shape))
for i in range(dataset.shape[0]):
    related[i][1] = dataset.iloc[i][-1][-1]
    related[i][0] = dataset.iloc[i][-2][-1]

related = related - 1
print(related.shape)
#for i in range(related.shape[0]):
    #for j in range(related.shape[1]):
        #related[i][j] = int(related[i][j])

related[:20]

(3598, 2)
(3598, 2)


array([[0., 2.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [0., 3.],
       [0., 2.],
       [0., 1.],
       [0., 5.],
       [1., 3.],
       [1., 5.],
       [1., 2.],
       [2., 3.],
       [2., 5.],
       [3., 5.],
       [4., 0.],
       [4., 1.],
       [4., 3.],
       [4., 5.],
       [4., 2.],
       [6., 2.]])

In [7]:
print (dataset.iloc[0])

p1    F0002/MID1
p2    F0002/MID3
Name: 0, dtype: object


In [8]:
from collections import defaultdict
#keeps all photos path in a dictionary
n_members = []

allPhotos = defaultdict(list)
for family in sorted(glob.glob(root_path + "/train/*")):
    print(family)
    fg = 0
    for mem in glob.glob(family+'/*'):
        #print(mem)
        fg = fg+1
    print(fg)
    n_members.append(fg)
    count_F[family[-5:]] = fg
    #print(fg)
    #n_mids.append(fg)
        #for photo in glob.glob(mem+'/*'):
            #allPhotos[mem].append(photo)

#list of all members with valid photo
#ppl = list(allPhotos.keys())
#ppl

/home/jayesh/Documents/ML&DL_stuff/NorthEastern_SMILE/recognizing-faces-in-the-wild/train/F0002
3
/home/jayesh/Documents/ML&DL_stuff/NorthEastern_SMILE/recognizing-faces-in-the-wild/train/F0005
3
/home/jayesh/Documents/ML&DL_stuff/NorthEastern_SMILE/recognizing-faces-in-the-wild/train/F0009
7
/home/jayesh/Documents/ML&DL_stuff/NorthEastern_SMILE/recognizing-faces-in-the-wild/train/F0010
4
/home/jayesh/Documents/ML&DL_stuff/NorthEastern_SMILE/recognizing-faces-in-the-wild/train/F0016
5
/home/jayesh/Documents/ML&DL_stuff/NorthEastern_SMILE/recognizing-faces-in-the-wild/train/F0017
7
/home/jayesh/Documents/ML&DL_stuff/NorthEastern_SMILE/recognizing-faces-in-the-wild/train/F0020
10
/home/jayesh/Documents/ML&DL_stuff/NorthEastern_SMILE/recognizing-faces-in-the-wild/train/F0022
5
/home/jayesh/Documents/ML&DL_stuff/NorthEastern_SMILE/recognizing-faces-in-the-wild/train/F0023
6
/home/jayesh/Documents/ML&DL_stuff/NorthEastern_SMILE/recognizing-faces-in-the-wild/train/F0024
5
/home/jayesh/Docume

In [9]:
len(count_F)
count_F[min(count_F)]

3

In [10]:
n_members = np.array(n_members)

In [11]:
import glob
import os
root=os.getcwd()
print(root)
allfamadd=list()
allfam=list()
for family in sorted(glob.glob(root+"/train/*")):
    #print(family)
    allfamadd.append(family)
    allfam.append(str(family)[-5:])

print(allfam)


/home/jayesh/Documents/ML&DL_stuff/NorthEastern_SMILE/recognizing-faces-in-the-wild
['F0002', 'F0005', 'F0009', 'F0010', 'F0016', 'F0017', 'F0020', 'F0022', 'F0023', 'F0024', 'F0030', 'F0031', 'F0036', 'F0038', 'F0039', 'F0040', 'F0041', 'F0044', 'F0049', 'F0050', 'F0051', 'F0052', 'F0054', 'F0058', 'F0059', 'F0063', 'F0064', 'F0068', 'F0070', 'F0074', 'F0077', 'F0081', 'F0086', 'F0091', 'F0093', 'F0097', 'F0099', 'F0101', 'F0105', 'F0106', 'F0109', 'F0110', 'F0112', 'F0113', 'F0118', 'F0119', 'F0122', 'F0123', 'F0124', 'F0126', 'F0128', 'F0129', 'F0130', 'F0132', 'F0134', 'F0135', 'F0137', 'F0138', 'F0142', 'F0146', 'F0150', 'F0151', 'F0154', 'F0155', 'F0157', 'F0158', 'F0159', 'F0160', 'F0161', 'F0162', 'F0164', 'F0165', 'F0167', 'F0168', 'F0169', 'F0170', 'F0174', 'F0178', 'F0179', 'F0183', 'F0188', 'F0191', 'F0192', 'F0194', 'F0195', 'F0196', 'F0197', 'F0198', 'F0199', 'F0202', 'F0203', 'F0206', 'F0209', 'F0210', 'F0211', 'F0212', 'F0214', 'F0215', 'F0216', 'F0225', 'F0227', 'F0228

In [12]:
dataset = pd.read_csv('train_relationships.csv')
#for i in range()
print(dataset.p1.head(10))
print('-------------')
print(dataset.p2.head(10))

0    F0002/MID1
1    F0002/MID2
2    F0005/MID1
3    F0005/MID3
4    F0009/MID1
5    F0009/MID1
6    F0009/MID1
7    F0009/MID1
8    F0009/MID2
9    F0009/MID2
Name: p1, dtype: object
-------------
0    F0002/MID3
1    F0002/MID3
2    F0005/MID2
3    F0005/MID2
4    F0009/MID4
5    F0009/MID3
6    F0009/MID2
7    F0009/MID6
8    F0009/MID4
9    F0009/MID6
Name: p2, dtype: object


In [13]:
countlist=list()
for j in range(len(allfam)):
    count=0
    for i in range(len(dataset.p1)):
        if(allfam[j]==dataset.p1.iloc[i][:5]):
            count=count+1
    countlist.append(count)
print(countlist)

[2, 2, 20, 5, 5, 16, 29, 6, 9, 4, 3, 9, 9, 8, 2, 1, 4, 1, 3, 2, 11, 5, 3, 10, 5, 1, 13, 9, 11, 6, 4, 11, 4, 13, 4, 3, 30, 28, 7, 8, 3, 3, 5, 4, 20, 3, 7, 20, 2, 5, 22, 13, 5, 1, 2, 2, 1, 2, 3, 9, 19, 2, 5, 6, 6, 15, 2, 10, 3, 7, 5, 19, 12, 4, 5, 5, 19, 2, 5, 9, 12, 3, 18, 7, 2, 3, 14, 9, 9, 8, 30, 31, 9, 3, 5, 5, 3, 14, 12, 5, 7, 5, 30, 4, 3, 11, 12, 2, 2, 2, 4, 2, 12, 2, 2, 3, 1, 4, 2, 17, 20, 1, 1, 1, 1, 3, 4, 23, 8, 7, 13, 5, 13, 9, 5, 11, 9, 5, 31, 9, 1, 4, 3, 2, 1, 21, 12, 9, 1, 4, 3, 5, 9, 36, 5, 11, 5, 17, 3, 5, 8, 2, 5, 31, 5, 2, 10, 36, 11, 5, 2, 24, 9, 5, 6, 1, 2, 7, 2, 3, 19, 13, 2, 23, 4, 6, 1, 10, 9, 18, 23, 4, 3, 5, 14, 2, 5, 10, 16, 2, 3, 4, 2, 2, 3, 14, 12, 2, 6, 3, 5, 3, 3, 9, 2, 9, 2, 7, 9, 1, 20, 1, 7, 3, 2, 5, 10, 1, 2, 4, 5, 5, 3, 3, 9, 14, 6, 5, 4, 8, 10, 5, 31, 6, 5, 5, 9, 4, 27, 2, 3, 8, 2, 17, 2, 6, 9, 7, 5, 13, 75, 2, 5, 3, 10, 14, 9, 1, 8, 2, 3, 7, 5, 7, 8, 19, 11, 9, 14, 3, 2, 4, 15, 1, 3, 19, 9, 5, 3, 11, 10, 9, 9, 1, 6, 1, 5, 10, 4, 2, 3, 3, 38, 2, 4, 9, 1

In [14]:
dataset.p1.iloc[4][:5]

'F0009'

In [15]:
n_members
print(len(n_members))
print(len(countlist))

470
470


In [16]:
related[:20]

array([[0., 2.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [0., 3.],
       [0., 2.],
       [0., 1.],
       [0., 5.],
       [1., 3.],
       [1., 5.],
       [1., 2.],
       [2., 3.],
       [2., 5.],
       [3., 5.],
       [4., 0.],
       [4., 1.],
       [4., 3.],
       [4., 5.],
       [4., 2.],
       [6., 2.]])

In [17]:
countlist

[2,
 2,
 20,
 5,
 5,
 16,
 29,
 6,
 9,
 4,
 3,
 9,
 9,
 8,
 2,
 1,
 4,
 1,
 3,
 2,
 11,
 5,
 3,
 10,
 5,
 1,
 13,
 9,
 11,
 6,
 4,
 11,
 4,
 13,
 4,
 3,
 30,
 28,
 7,
 8,
 3,
 3,
 5,
 4,
 20,
 3,
 7,
 20,
 2,
 5,
 22,
 13,
 5,
 1,
 2,
 2,
 1,
 2,
 3,
 9,
 19,
 2,
 5,
 6,
 6,
 15,
 2,
 10,
 3,
 7,
 5,
 19,
 12,
 4,
 5,
 5,
 19,
 2,
 5,
 9,
 12,
 3,
 18,
 7,
 2,
 3,
 14,
 9,
 9,
 8,
 30,
 31,
 9,
 3,
 5,
 5,
 3,
 14,
 12,
 5,
 7,
 5,
 30,
 4,
 3,
 11,
 12,
 2,
 2,
 2,
 4,
 2,
 12,
 2,
 2,
 3,
 1,
 4,
 2,
 17,
 20,
 1,
 1,
 1,
 1,
 3,
 4,
 23,
 8,
 7,
 13,
 5,
 13,
 9,
 5,
 11,
 9,
 5,
 31,
 9,
 1,
 4,
 3,
 2,
 1,
 21,
 12,
 9,
 1,
 4,
 3,
 5,
 9,
 36,
 5,
 11,
 5,
 17,
 3,
 5,
 8,
 2,
 5,
 31,
 5,
 2,
 10,
 36,
 11,
 5,
 2,
 24,
 9,
 5,
 6,
 1,
 2,
 7,
 2,
 3,
 19,
 13,
 2,
 23,
 4,
 6,
 1,
 10,
 9,
 18,
 23,
 4,
 3,
 5,
 14,
 2,
 5,
 10,
 16,
 2,
 3,
 4,
 2,
 2,
 3,
 14,
 12,
 2,
 6,
 3,
 5,
 3,
 3,
 9,
 2,
 9,
 2,
 7,
 9,
 1,
 20,
 1,
 7,
 3,
 2,
 5,
 10,
 1,
 2,
 4,
 5,
 5,
 3,
 3,
 9

In [19]:
i = 0
z = 0
for key in n_members:
    shape = key
    n_relations = countlist[i] 
    
#print(x[0])
    x_ans = []
    y_ans = []
    matrix = np.zeros((shape,shape))
    #print(matrix)
    print('-----------')
    print("shape",shape)
    print(n_relations)
    print('-----------')
    for t in range(z,z+n_relations):
        if related[t][0] < shape and related[t][1] < shape :
            print (related[t][0],related[t][1])
            matrix[int(related[t][0])][int(related[t][1])] = 1
            matrix[int(related[t][1])][int(related[t][0])] = 1
    print('-----------------')
    print('-----------------')
    print(z)
    z = z + n_relations
    print(z)
    print('-----------------')
    print('-----------------')
    for ix in range(shape):
        for jy in range(shape):
            if ix==jy:
                 continue
            elif matrix[ix][jy] == 0:
                x_ans.append(ix)
                y_ans.append(jy)
                if matrix[jy][ix] == 0:
                    matrix[jy][ix] = 2
    
    print('----------')
    print(x_ans)
    print(y_ans)
    print('-----------')
    print(matrix)
    print('-----------')
    print('****************************')
    x_ans.clear
    y_ans.clear
    i = i+1
            
#print(matrix)
#print(x_ans)
#print(y_ans)

-----------
shape 3
2
-----------
0.0 2.0
1.0 2.0
-----------------
-----------------
0
2
-----------------
-----------------
----------
[0]
[1]
-----------
[[0. 0. 1.]
 [2. 0. 1.]
 [1. 1. 0.]]
-----------
****************************
-----------
shape 3
2
-----------
0.0 1.0
2.0 1.0
-----------------
-----------------
2
4
-----------------
-----------------
----------
[0]
[2]
-----------
[[0. 1. 0.]
 [1. 0. 1.]
 [2. 1. 0.]]
-----------
****************************
-----------
shape 7
20
-----------
0.0 3.0
0.0 2.0
0.0 1.0
0.0 5.0
1.0 3.0
1.0 5.0
1.0 2.0
2.0 3.0
2.0 5.0
3.0 5.0
4.0 0.0
4.0 1.0
4.0 3.0
4.0 5.0
4.0 2.0
6.0 2.0
6.0 5.0
6.0 3.0
6.0 0.0
6.0 1.0
-----------------
-----------------
4
24
-----------------
-----------------
----------
[4]
[6]
-----------
[[0. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 2. 1. 0.]]
-----------
****************************
-----------
shape

 [2. 2. 1. 1. 1. 1. 1. 0.]]
-----------
****************************
-----------
shape 4
4
-----------
0.0 2.0
0.0 3.0
1.0 3.0
2.0 3.0
-----------------
-----------------
569
573
-----------------
-----------------
----------
[0, 1]
[1, 2]
-----------
[[0. 0. 1. 1.]
 [2. 0. 0. 1.]
 [1. 2. 0. 1.]
 [1. 1. 1. 0.]]
-----------
****************************
-----------
shape 4
5
-----------
0.0 3.0
1.0 3.0
1.0 0.0
2.0 0.0
2.0 3.0
-----------------
-----------------
573
578
-----------------
-----------------
----------
[1]
[2]
-----------
[[0. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 2. 0. 1.]
 [1. 1. 1. 0.]]
-----------
****************************
-----------
shape 4
5
-----------
0.0 2.0
0.0 1.0
2.0 1.0
3.0 1.0
3.0 0.0
-----------------
-----------------
578
583
-----------------
-----------------
----------
[2]
[3]
-----------
[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 0.]
 [1. 1. 2. 0.]]
-----------
****************************
-----------
shape 7
19
-----------
0.0 3.0
0.0 4.0
0.0 5.0
0.0 6.0
1.0 3

832
862
-----------------
-----------------
----------
[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 9, 9, 10]
[4, 5, 7, 8, 9, 10, 2, 6, 7, 9, 10, 4, 8, 9, 10, 7, 9, 10, 5, 6, 7, 8, 9, 10, 11, 6, 9, 10, 11, 7, 8, 9, 10, 8, 9, 10, 11, 9, 10, 11, 10, 11, 11]
-----------
[[1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1.]
 [1. 2. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1.]
 [1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1.]
 [2. 1. 2. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 1. 1. 1. 2. 0. 0. 1. 1. 0. 0. 0.]
 [1. 2. 1. 1. 2. 2. 0. 0. 0. 0. 0. 1.]
 [2. 2. 1. 2. 2. 1. 2. 0. 0. 0. 0. 0.]
 [2. 1. 2. 1. 2. 1. 2. 2. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 0. 0. 0.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 0. 0.]
 [1. 1. 1. 1. 2. 2. 1. 2. 2. 2. 2. 0.]]
-----------
****************************
-----------
shape 5
4
-----------
0.0 4.0
0.0 2.0
1.0 2.0
-----------------
-----------------
862
866
-----------------
-----------------
--------

1.0 3.0
-----------------
-----------------
1382
1393
-----------------
-----------------
----------
[1, 2]
[2, 3]
-----------
[[0. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 2. 0. 0.]
 [1. 1. 2. 0.]]
-----------
****************************
-----------
shape 4
5
-----------
0.0 1.0
2.0 0.0
2.0 1.0
3.0 0.0
3.0 1.0
-----------------
-----------------
1393
1398
-----------------
-----------------
----------
[2]
[3]
-----------
[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 0.]
 [1. 1. 2. 0.]]
-----------
****************************
-----------
shape 3
2
-----------
0.0 1.0
2.0 1.0
-----------------
-----------------
1398
1400
-----------------
-----------------
----------
[0]
[2]
-----------
[[0. 1. 0.]
 [1. 0. 1.]
 [2. 1. 0.]]
-----------
****************************
-----------
shape 8
24
-----------
0.0 3.0
0.0 4.0
0.0 5.0
0.0 2.0
1.0 2.0
1.0 4.0
1.0 5.0
1.0 3.0
2.0 4.0
2.0 5.0
2.0 3.0
3.0 4.0
3.0 5.0
4.0 5.0
6.0 5.0
6.0 2.0
6.0 3.0
6.0 0.0
6.0 4.0
7.0 3.0
7.0 5.0
7.0 4.0
7.0 0.0
7.0 2.0
--------------

-----------------
1923
1928
-----------------
-----------------
----------
[1]
[2]
-----------
[[0. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 2. 0. 1.]
 [1. 1. 1. 0.]]
-----------
****************************
-----------
shape 5
9
-----------
0.0 4.0
0.0 3.0
1.0 4.0
1.0 0.0
1.0 3.0
2.0 3.0
2.0 4.0
2.0 0.0
3.0 4.0
-----------------
-----------------
1928
1937
-----------------
-----------------
----------
[1]
[2]
-----------
[[0. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1.]
 [1. 2. 0. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]]
-----------
****************************
-----------
shape 3
4
-----------
0.0 2.0
0.0 1.0
1.0 2.0
-----------------
-----------------
1937
1941
-----------------
-----------------
----------
[]
[]
-----------
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
-----------
****************************
-----------
shape 9
27
-----------
0.0 6.0
0.0 1.0
0.0 5.0
0.0 4.0
0.0 2.0
0.0 3.0
1.0 2.0
3.0 4.0
3.0 6.0
3.0 5.0
4.0 5.0
4.0 6.0
5.0 6.0
7.0 0.0
7.0 2.0
7.0 4.0
7.0 1.0
7.0 6.0
7.0 3.0
7.0 5.0
8.0 4.0
8.

-----------------
-----------------
2432
2436
-----------------
-----------------
----------
[0, 0]
[1, 2]
-----------
[[0. 0. 0. 1.]
 [2. 0. 1. 1.]
 [2. 1. 0. 1.]
 [1. 1. 1. 0.]]
-----------
****************************
-----------
shape 5
9
-----------
0.0 4.0
0.0 3.0
1.0 0.0
1.0 3.0
1.0 4.0
2.0 4.0
2.0 0.0
2.0 3.0
3.0 4.0
-----------------
-----------------
2436
2445
-----------------
-----------------
----------
[1]
[2]
-----------
[[0. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1.]
 [1. 2. 0. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]]
-----------
****************************
-----------
shape 7
10
-----------
0.0 4.0
0.0 2.0
0.0 5.0
1.0 2.0
2.0 5.0
2.0 4.0
3.0 4.0
3.0 5.0
4.0 5.0
6.0 0.0
-----------------
-----------------
2445
2455
-----------------
-----------------
----------
[0, 0, 1, 1, 1, 1, 2, 2, 3, 4, 5]
[1, 3, 3, 4, 5, 6, 3, 6, 6, 6, 6]
-----------
[[0. 0. 1. 0. 1. 1. 1.]
 [2. 0. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 1. 1. 0.]
 [2. 2. 2. 0. 1. 1. 0.]
 [1. 2. 1. 1. 0. 1. 0.]
 [1. 2. 1. 1. 1. 0. 

4.0 3.0
-----------------
-----------------
3045
3050
-----------------
-----------------
----------
[0, 0, 1, 1, 2]
[1, 4, 3, 4, 4]
-----------
[[0. 0. 1. 1. 0.]
 [2. 0. 1. 0. 0.]
 [1. 1. 0. 1. 0.]
 [1. 2. 1. 0. 1.]
 [2. 2. 2. 1. 0.]]
-----------
****************************
-----------
shape 5
4
-----------
0.0 3.0
2.0 3.0
3.0 4.0
-----------------
-----------------
3050
3054
-----------------
-----------------
----------
[0, 0, 0, 1, 1, 1, 2]
[1, 2, 4, 2, 3, 4, 4]
-----------
[[0. 0. 0. 1. 0.]
 [2. 0. 0. 0. 0.]
 [2. 2. 0. 1. 0.]
 [1. 2. 1. 0. 1.]
 [2. 2. 2. 1. 0.]]
-----------
****************************
-----------
shape 7
16
-----------
0.0 2.0
0.0 3.0
1.0 4.0
1.0 3.0
1.0 2.0
2.0 4.0
2.0 3.0
2.0 5.0
3.0 4.0
3.0 5.0
4.0 5.0
5.0 0.0
6.0 0.0
6.0 2.0
6.0 3.0
6.0 4.0
-----------------
-----------------
3054
3070
-----------------
-----------------
----------
[0, 0, 1, 1, 5]
[1, 4, 5, 6, 6]
-----------
[[0. 0. 1. 1. 0. 1. 1.]
 [2. 0. 1. 1. 1. 0. 0.]
 [1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 0

3.0 4.0
4.0 5.0
-----------------
-----------------
3342
3350
-----------------
-----------------
----------
[0, 1, 1, 1, 2, 2, 2]
[2, 3, 4, 5, 3, 4, 5]
-----------
[[0. 1. 0. 1. 1. 1.]
 [1. 0. 1. 0. 0. 0.]
 [2. 1. 0. 0. 0. 0.]
 [1. 2. 2. 0. 1. 1.]
 [1. 2. 2. 1. 0. 1.]
 [1. 2. 2. 1. 1. 0.]]
-----------
****************************
-----------
shape 4
2
-----------
0.0 1.0
3.0 2.0
-----------------
-----------------
3350
3352
-----------------
-----------------
----------
[0, 0, 1, 1]
[2, 3, 2, 3]
-----------
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [2. 2. 0. 1.]
 [2. 2. 1. 0.]]
-----------
****************************
-----------
shape 5
7
-----------
0.0 2.0
1.0 4.0
1.0 2.0
1.0 3.0
2.0 4.0
2.0 3.0
3.0 4.0
-----------------
-----------------
3352
3359
-----------------
-----------------
----------
[0, 0, 0]
[1, 3, 4]
-----------
[[0. 0. 1. 0. 0.]
 [2. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [2. 1. 1. 0. 1.]
 [2. 1. 1. 1. 0.]]
-----------
****************************
-----------
shape 4
5
-----------
0.0

In [92]:
countlist[127]

23